-- AlterTable
ALTER TABLE "TableGeneral" ALTER COLUMN "Metros" SET DATA TYPE TEXT,
ALTER COLUMN "Precio_Dolar" SET DATA TYPE TEXT,
ALTER COLUMN "Precio_Soles" SET DATA TYPE TEXT,
ALTER COLUMN "Etapas" SET DATA TYPE TEXT,
ALTER COLUMN "Independizado" SET DATA TYPE TEXT,
ALTER COLUMN "Servicios_Basicos" SET DATA TYPE TEXT,
ALTER COLUMN "Fecha_Entrega" SET DATA TYPE TEXT;
